### ISSUE TITLE
Processing results can panic on vulnerabilities with missing `DataSource`

### ISSUE THREAD

**Issue by michaelsauter** [aquasecurity/trivy-plugin-aqua#319]
It looks like `addVulnerabilitiesResults` https://github.com/aquasecurity/trivy-plugin-aqua/blob/master/pkg/processor/result_processor.go#L160 can panic:

```
2022-10-11T14:43:04.238+0200    ERROR   failed running plugin, got panic: %!(EXTRA runtime.errorString=runtime error: invalid memory address or nil pointer dereference, string=goroutine 1 [running]:
runtime/debug.Stack()
        /opt/hostedtoolcache/go/1.18.5/x64/src/runtime/debug/stack.go:24 +0x68
main.main.func1()
        /home/runner/work/trivy-plugin-aqua/trivy-plugin-aqua/cmd/aqua/main.go:52 +0x38
panic({0x106e3eac0, 0x10a8a4580})
        /opt/hostedtoolcache/go/1.18.5/x64/src/runtime/panic.go:838 +0x204
github.com/aquasecurity/trivy-plugin-aqua/pkg/processor.addVulnerabilitiesResults({{0x1400144b500, 0x28}, {0x1055c2dcf, 0x7}, {0x140035440d8, 0x6}, {0x0, 0x0, 0x0}, {0x14003304000, ...}, ...}, ...)
        /home/runner/work/trivy-plugin-aqua/trivy-plugin-aqua/pkg/processor/result_processor.go:160 +0x338
github.com/aquasecurity/trivy-plugin-aqua/pkg/processor.ProcessResults({0x140010a2000, 0x6, 0x0?}, {0x0, 0x0, 0x0}, 0x0?)
        /home/runner/work/trivy-plugin-aqua/trivy-plugin-aqua/pkg/processor/result_processor.go:104 +0x450
main.runScan(_, {_, _, _}, {{{0x1055e36b3, 0xa}, 0x0, 0x0, 0x0, 0x0, ...}, ...})
        /home/runner/work/trivy-plugin-aqua/trivy-plugin-aqua/cmd/aqua/main.go:314 +0x70c
main.initCommand.func3(0x14002977180, {0x140033c7530, 0x1, 0x3})
        /home/runner/work/trivy-plugin-aqua/trivy-plugin-aqua/cmd/aqua/main.go:218 +0x13c
github.com/spf13/cobra.(*Command).execute(0x14002977180, {0x140033c7500, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:872 +0x4d0
github.com/spf13/cobra.(*Command).ExecuteC(0x14002976780)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x354
github.com/spf13/cobra.(*Command).Execute(...)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/runner/work/trivy-plugin-aqua/trivy-plugin-aqua/cmd/aqua/main.go:88 +0x42c
)
2022-10-11T14:43:04.243+0200    FATAL   plugin error: unable to run aqua plugin: plugin exec: exit status 1
```

Only happens on some vulnerabilities, when I filter by severity such that the offending vulnerability is not in the result, the panic does not happen.

**Comment by VaismanLior** [comment]
Hey @michaelsauter,
Thanks for reporting this issue.
We'll get it fixed shortly.

**Comment by VaismanLior** [comment]
Should be fixed now, please let us know if you have any other issues.
